### ISSUE TITLE
Some deps are not only depend on the package-lock file, but also the OS, so it’s better to use Debian docker to generate the site,not alphine, because it use musl

### ISSUE THREAD

**Issue by cielpy** [sma11black/hexo-action#10]
Such as node-sass

**Comment by cielpy** [comment]
Show case https://github.com/cielpy/hexo-blog/runs/1032366119?check_suite_focus=true#step:7:34

**Comment by sma11black** [comment]
Thank you for your suggestion. The choice of the parent image is indeed my poor consideration. I have corrected in the new version released, refer to [v1.0.3](https://github.com/sma11black/hexo-action/releases/tag/v1.0.3).

For a smaller file size, I chose the `node:12-buster-slim` tag version. If you have better suggestions, you can also put them here.

**Comment by cielpy** [comment]
I will try the new version, thanks for your work.
