### ISSUE TITLE
checkout using SSH?

### ISSUE THREAD

**Issue by huntertran** [sma11black/hexo-action#11]
It seems that the default method for checkout is HTTPS
can we have an option to "switch" to using SSH instead?

**Comment by sma11black** [comment]
Do you mean the checkout step in the workflow file?
```yaml
...
steps:
- name: Checkout
  uses: actions/checkout@v1
```
For the specific configuration of this part, you can check the official [repository](https://github.com/actions/checkout) for details.

If you care about the `sync_deploy_history.js`, you should specify the deployment repository and method in your hexo configuration file, which is the **_config.yml** file. Its implementation is modified according to the official git deployer plug-in `hexo-deployer-git`.
