### ISSUE TITLE
Commit to other repository?

### ISSUE THREAD

**Issue by ghost** [sma11black/hexo-action#16]
my blog is have some serect data,it was don't public
so i create a private repository to deploy the blog.
can i commit compired data to other repository?

**Comment by sma11black** [comment]
@gamecss Yes. This GitHub Action can be used regardless of whether your *Github Pages repo* and *hexo source code repo* are private or public.
The most critical settings are the `Deploy Key` and `Secret` settings, please refer to the [Usage](https://github.com/sma11black/hexo-action#usage) part of README.

**Comment by ghost** [comment]
Thanks.I change hexo's _config.yml "deploy" to realization.
