### ISSUE TITLE
Name or service not known  fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by CrazyThursday-Vme50** [sma11black/hexo-action#17]
when the job run to "deploy",an error was encountered,what should I do to solve it
![图片](https://user-images.githubusercontent.com/50069659/126866341-1c7f6556-5396-4d63-86b7-f16197f377af.png)

And I have two github accounts in my computer,for each account I create different ssh key to deploy blog locally, set host and hostname in the config file under the .ssh file folder .    
In the hexo config file my deploy part config as the pic shows
![图片](https://user-images.githubusercontent.com/50069659/126867213-ce287fbb-5ceb-4fdf-8913-845b73d32211.png)

I have created the other key to deploy CI and set the deploy key and the private key in repositories.

At last , apologize for my poor English.I will be very grateful for reply.

**Comment by sma11black** [comment]
As the error message in the picture shows, as far as I know, there should be no domain name like `gm-github`. The last repository link you commented should work.

**Comment by CrazyThursday-Vme50** [comment]
What should I do to solve it, Use the last config option "repo:git@github.com:greedymonkey/greedymonkey.github.io.git"?

**Comment by sma11black** [comment]
Yes. In addition, you can first try to deploy from your local machine to verify the correctness of the configuration.

**Comment by CrazyThursday-Vme50** [comment]
Thank you very much!! It deploys successful!
It seems that I know how to config the repo option to deploy my blog.
If I want to use the CI to deploy, I have to set the 'repo' option as 'git@github.com',but in my local machine I need to set 'repo' as 'git@gm-github',because I have two git accounts in my computer, I need to set alias to deploy blogs in my two accounts respectively. Thanks again.
