### ISSUE TITLE
The npm version in docker is too low

### ISSUE THREAD

**Issue by cacaview** [sma11black/hexo-action#20]
I got an error from npm when deploying hexo
this is the error log：
[https://github.com/byg-software/byg-software-Official-website/runs/8010043706?check_suite_focus=true](url)
After looking through the sources, I think the cause of the problem may be the version of npm
Because the npm version I am using is 7.5.2

**Comment by sma11black** [comment]
To make the tool work for most people, I followed the [version requirements](https://hexo.io/docs/index.html#Requirements) on the official website.
If you need to use a lower version, you can consider **fork** project to modify the **docker base image** to the lower node version, or it is recommended to **upgrade** the local node environment to a version that meets the official requirements.

The modified Dockerfile can be like this:
```Dockerfile
FROM node:7-slim

# other statement...
```
