### ISSUE TITLE
fatal: could not read Username for 'https://github.com': No such device or address

### ISSUE THREAD

**Issue by dl8sd11** [sma11black/hexo-action#5]
I did set the deploy url using ssh, it also works for me locally without the username prompt.

![2020-05-17-19-37-53](https://user-images.githubusercontent.com/19171021/82143364-e6dc1500-9875-11ea-868d-dc61ae805a29.png)

But it seems like the job got prompt for username.

![2020-05-17-19-36-39](https://user-images.githubusercontent.com/19171021/82143351-c8761980-9875-11ea-8a77-3f7c667e48fd.png)

**Comment by dl8sd11** [comment]
After a few trail, I found out the GitHub page repo should not be private.

**Comment by farukcan** [comment]
Same problem but my repo is public
```
fatal: could not read Username for 'https://github.com': No such device or address
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Error: Spawn failed
```

**Comment by sma11black** [comment]
@farukcan Most likely you can fix it by replacing the **HTTPS URL** with **SSH URL** (`git@github.com: ...`).

For example, this is a working code snippet in `config.yml`:
```yaml
deploy:
  type: git
  repo: git@github.com:<username>/<username>.github.io.git
  branch: master
```

I think this problem is from `hexo-deploy-git` package. It does not support the HTTPS URL exactly.

**Comment by Caffreyfans** [comment]
> @farukcan Most likely you can fix it by replacing the **HTTPS URL** with **SSH URL** (`git@github.com: ...`).
> 
> For example, this is a working code snippet in `config.yml`:
> 
> ```yaml
> deploy:
>   type: git
>   repo: git@github.com:<username>/<username>.github.io.git
>   branch: master
> ```
> 
> I think this problem is from `hexo-deploy-git` package. It does not support the HTTPS URL exactly.

That's work for me. Thanks.
