### ISSUE TITLE
SSH Key doesnt work

### ISSUE THREAD

**Issue by farukcan** [sma11black/hexo-action#6]
Hi,
I have a problem about keys

```
Warning: Permanently added the RSA host key for IP address '140.82.114.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
```

**Comment by sma11black** [comment]
@farukcan Have you tried to regenerate the SSH key? There are some suggested steps for you to confirm:

1. Generate a new pair of ssh public and private keys

2. Add the **public key** to your *xxx.github.io* repo as **Deploy keys**

3. Add the **private key** to your *hexo source code* repo as **Secrets**

4. Finally re-trigger github action

> Here are detailed setup steps: [Setup Deploy keys and Secrets](https://github.com/sma11black/hexo-action#step-1-setup-deploy-keys-and-secrets)

---
Some help documents may be helpful to you:

- [Error: Permission denied (publickey)](https://help.github.com/en/github/authenticating-to-github/error-permission-denied-publickey)

- [Generating a new SSH key](https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#generating-a-new-ssh-key)

**Comment by farukcan** [comment]
Thank you, very much.
I found the problem after 4 hours : I used passphrase
Conclusion : You must not use passphase when creating ssh keys
I want to cry 🥇
