### ISSUE TITLE
how do I config if I would like to install more dependencies for themes

### ISSUE THREAD

**Issue by fuzheng1998** [sma11black/hexo-action#9]
I have a theme need `Hexo-render-scss`, how I can add it to your hexo action

**Comment by sma11black** [comment]
@fuzheng1998 You can try to add this dependency in the `package.json` file. Then regenerate the **`package-lock.json`** file. For detials, please refer to: [How to install additional third party node modules](https://github.com/sma11black/hexo-action#how-to-install-additional-third-party-node-modules).
